language: python

#which versions of python to test against
python:
  - "2.7"
  - "3.6"

# command to install dependencies
install:
  - pip install codecov
  - pip install coverage

script: 
  - python -m unittest discover -v ./ # command to run unit test
  - coverage run ./test.py # command to run code coverage
  
after_success:
 - codecov --token=c74dd386-73e2-4ba9-95d5-917823961198 # upload coverage report to codecov.io

deploy:
  provider: s3
  access_key_id: AKIAIINTJMOHJH3BM2WA
  secret_access_key: ha+/u865mk7e00D8BDkV0gxmmKz4hSD70T991vem94KSBhqwOKLQ1y4pY9ioAwXUYMXIC5PL94RMcV0L8lMhauxiTd5OBP+rkvNdwjrIPvtKF00Y6gWDOTLywH0Mo6e7ZXDE042FxevIVAqqePqtGuTa0VP/QqrLadthKUouqFCDK0HlZXmLg8nfUr/O7S1wRhULSNZrpNZtoIIo51kBpmZselqz/gU66NbP7EaShSxDxoK/dtdfrk6oa7ecB+RKh9z2wxoaTKPiQ7Tf1Xc/czl7no3ktuue3QVg9IaOeRXUnd3a1xqizTqg26APJ45Gkmtpe6Iy0HKGnavVj34XlPk4raclsrbfzSUo8qH+3R8/670upFcpDLuCVSSV9JLk92sWONW9LbkNUgDOsDKrqVxH8hUx3OE9yNyeLYZyLGjZXf2xqZ2NJFUSyjsM4oVa90bWcACR+qGm/L1uSZCcly9t467N4y+KZdVpea1KBlPqTP3lvC6Vp1lW6xUhkh6HN14GVuRqLTMsSNoMV7WugM+2yFV3xyeVPFZk4OwdMwFIeEhwKYqv0y4LNrLzRUffnnOuKtcQOtQ038oXqSiLT4fkiOA4uTsHr3lIQgubvkonvz3FrMid1IV+UtLRQgwWRVTky6gvTTEoBWx5UNTL8G8Y6CknE7XgWkAfZE6npW0=
  bucket: https://cps847group19.s3.amazonaws.com/index.html
  local-dir: ./index.html
  region: us-east-1
