language: python

#which versions of python to test against
python:
  - "2.7"
  - "3.6"

# command to install dependencies
install:
  - pip install codecov
  - pip install coverage

script: 
  - python -m unittest discover -v ./ # command to run unit test
  - coverage run ./test.py # command to run code coverage
  
after_success:
 - codecov --token=c74dd386-73e2-4ba9-95d5-917823961198 # upload coverage report to codecov.io

deploy:
  provider: s3
  access_key_id: AKIAJSL4R2PWM6V5KH3Q
  secret_access_key: 
    secure: MlCstbAVyKiMeC5VUb62ewji6c5eSkew25K3CdWxiG/5K8fpXzZ7XRr/elOBFVQbTIiwSK5AbZyUipk8LoLaCXFsKJFZF71e0TrSzqyDCmTMVYhEBQIUcIN1jW3ORsokLQzhXjZI29gTW5ghkFsX5WcfaT5a2v+ejyZsK4a+x2w4vzPpgrVcpcOxTiR3+k6p4LCzGVbRZltZNm8jqzwDDtsSBnKBv9TeWkqNVHg3rL1upK2Mlgt/P0+so8PaoA8WMmXKB0TshhkZSpBWyjFOqYA+fSHpvHVFCuYwg8S8JPbxqYQuCFuhTDsvPp2Np/EoHS62oQY9EyywRl6c4y4t6X8a02OV10GJiCQHVtiPoKpWh4T8Cl7O8t4X+oxwcbgXgHVZCOO9iGIXrlMZbsAjk+pMGdLKODS68FeoGwgRhsmpkkVyTAkUS+oOle9Me+PU9FSNZXnQAIOIZFFI8JgE1ug6FamRlp4r9JyUTFzHP35Kkg33y8F9eesLxEScocfIJvfHcRkcB4BmZOnoKInvOslh2VivwuCe3xr2ccnoM0GvE6XlnufCLN95B7nsoUhy22HReE1VEKUc7+eU1Kbin2cTgQdLxfGr/2eBIlViVUbqr+8D8MJU50jtaZh4QS0ov5aphYm61hlHEjeh8U5SKT8E4TRtLog9nH6FJBM0afs=
  bucket: https://cps847group19.s3.amazonaws.com/index.html
  local-dir: ./index.html
  region: us-east-1
